id: I3B7138E7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:20:06+00:00'
last_modified: '2022-06-08T11:05:40.733154+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20131
  title: གཙང་པོའི་ཕ་རོལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C389:
      image_group_id: I1KG14900
      title: ''
      total_pages: 604
      order: 1
      base_file: C389.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
