id: P009446
initial_creation_type: ocr
source_metadata:
  id: bdr:W20131
  title: གཙང་པོའི་ཕ་རོལ།
  author: ''
  volumes:
    5d87b29227d24411899b538b2d0f104d:
      image_group_id: I1KG14900
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
